---
- name: "Create {{ ctrld_config_dir }}"
  ansible.builtin.file:
    path: "{{ ctrld_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"

- name: "Create {{ ctrld_config_dir }}/ctrld.toml"
  ansible.builtin.file:
    path: "{{ ctrld_config_dir }}/ctrld.toml"
    owner: "{{ ctrld_user }}"
    group: "{{ ctrld_group }}"
    mode: "u=rw,g=r,o=r"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: "Configure {{ ctrld_config_dir }}/ctrld.toml"
  ansible.builtin.template:
    src: "ctrld.toml"
    dest: "{{ ctrld_config_dir }}/ctrld.toml"
    owner: "{{ ctrld_user }}"
    group: "{{ ctrld_group }}"
    mode: "u=rw,g=r,o=r"
  notify: "reload ctrld"
  when: ctrld_config != ""
